#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1

CONFIG=/etc/mqtt-io/mqtt-io.yml

PROG=/usr/bin/python3 -m mqtt_io "$CONFIG"

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param file "$CONFIG"
	procd_set_param pidfile /var/run/mqtt-io.pid
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn \
		${respawn_threshold:-3600} \
		${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param term_timeout 60
	procd_close_instance
}
